In [6]:
import duckdb
import pandas as pd

In [5]:
sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                              name
0        bronze_parking_violdation
1  bronze_parking_violdation_codes
2                      first_model
3                        ref_model

In [10]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
FROM read_csv_auto(
  'data/dof_parking_violation_codes.csv',
  normalize_names=True
  )
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 AS
SELECT *
FROM read_csv_auto(
  'data/parking_violations_issued_fiscal_year_2023_sample.csv',
  normalize_names=True
  )
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
  con.sql(sql_query_import_1)
  con.sql(sql_query_import_2)

In [12]:
sql_query = '''
show tables
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                               name
0    bronze_parking_violation_codes
1         bronze_parking_violations
2         bronze_parking_violdation
3   bronze_parking_violdation_codes
4                       first_model
5               gold_ticket_metrics
6             gold_vehicles_metrics
7           parking_violation_codes
8           parking_violations_2023
9                         ref_model
10   silver_parking_violation_codes
11        silver_parking_violations
12         silver_violation_tickets
13        silver_violation_vehicles

In [6]:
sql_query = '''
SELECT * from ref_model
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   violation_count
0               97

In [8]:
sql_query = '''
SELECT
    violation_code,
    SUM(fee_usd) AS total_revenue_usd
FROM
    silver_parking_violation_codes
GROUP BY
    violation_code
HAVING
    NOT(total_revenue_usd >= 1)
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   violation_code  total_revenue_usd
0              41                0.0

In [9]:
sql_query = '''
select * from "prod_nyc_parking_violations"."main_dbt_test__audit"."violation_codes_revenue"
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   violation_code  total_revenue_usd
0              41                0.0

In [7]:
sql_query = '''
show tables
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                               name
0    bronze_parking_violation_codes
1         bronze_parking_violations
2         bronze_parking_violdation
3   bronze_parking_violdation_codes
4                       first_model
5               gold_ticket_metrics
6             gold_vehicles_metrics
7           parking_violation_codes
8           parking_violations_2023
9                         ref_model
10   silver_parking_violation_codes
11        silver_parking_violations
12         silver_violation_tickets
13        silver_violation_vehicles

In [18]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
FROM read_csv_auto(
  'data/dof_parking_violation_codes.csv',
  normalize_names=True
  )
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 AS
SELECT *
FROM read_csv_auto(
  'data/parking_violations_issued_fiscal_year_2023_sample.csv',
  normalize_names=True
  )
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
  con.sql(sql_query_import_1)
  con.sql(sql_query_import_2)

In [21]:
sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

Empty DataFrame
Columns: [name]
Index: []

In [22]:
sql_query = '''
show tables
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                      name
0  parking_violation_codes
1  parking_violations_2023

In [23]:
sql_query = '''
SELECT * FROM parking_violation_codes LIMIT 5
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,code,definition,manhattan_96th_st_below,all_other_areas
0,1,FAILURE TO DISPLAY BUS PERMIT,515,515
1,2,NO OPERATOR NAM/ADD/PH DISPLAY,515,515
2,3,UNAUTHORIZED PASSENGER PICK-UP,515,515
3,4,BUS PARKING IN LOWER MANHATTAN,115,115
4,5,BUS LANE VIOLATION,250,250

In [8]:
sql_query = '''
SELECT * FROM gold_ticket_metrics
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

    violation_code  ticket_count  total_revenue_usd
0               36         37064          1853200.0
1                5          3477           869250.0
2               21         12149           789685.0
3               14          5047           580405.0
4               40          3902           448730.0
..             ...           ...                ...
71              23             1               60.0
72              41            18                0.0
73              94             1                NaN
74              95             4                NaN
75               0            14                NaN

[76 rows x 3 columns]

In [11]:
sql_query = '''
SELECT * FROM gold_vehicles_metrics
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   registration_state  ticket_count
0                  NJ          9258
1                  PA          3514
2                  FL          2414
3                  CT          1787
4                  GA           840
..                ...           ...
57                 AB             1
58                 NB             1
59                 BC             1
60                 PE             1
61                 SK             1

[62 rows x 2 columns]